In [1]:
import pandas as pd

final_report = pd.read_csv(
    "tests/preparation_data/example/test_data_res_FinalReport.txt", sep="\t", skiprows=9
)
final_report

,SNP Name,Sample ID,Allele1 - AB,Allele2 - AB,Chr,Position
0,BovineHD2400000076,SAMPLE0,A,A,24,112601
1,BovineHD2400000069,SAMPLE0,A,A,24,163270
2,Hapmap54014-rs29018901,SAMPLE0,A,A,24,300821
3,BovineHD4100016339,SAMPLE0,A,B,24,335857
4,ARS-BFGL-NGS-103469,SAMPLE0,A,A,24,391651
...,...,...,...,...,...,...
26124,BovineHD2400018199,SAMPLE16,A,B,24,61954180
26125,BTB-01890193,SAMPLE16,A,B,24,61991351
26126,BovineHD2400018253,SAMPLE16,B,B,24,62039634
26127,ARS-BFGL-NGS-29191,SAMPLE16,B,B,24,62127707
26128,BovineHD0700020755,SAMPLE16,A,B,24,62179612

In [2]:
sample_map = pd.read_csv(
    "tests/preparation_data/example/test_data_res_SampleMap.txt", sep="\t"
)
sample_map

,Index,Name,ID,Gender,Plate,Well,Group,Parent1,Parent2,Replicate,SentrixPosition
0,NaN,NaN,SAMPLE0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,SAMPLE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,SAMPLE2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,SAMPLE3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,SAMPLE4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,SAMPLE5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,SAMPLE6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,SAMPLE7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,SAMPLE8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,SAMPLE9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,SAMPLE10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,SAMPLE11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,SAMPLE12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,SAMPLE13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,SAMPLE14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,SAMPLE15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,SAMPLE16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
snp_map = pd.read_csv(
    "tests/preparation_data/example/test_data_res_SNPMap.txt", sep="\t"
)

snp_map

,Index,Name,Chromosome,Position,GenTrain Score,SNP,ILMN_Strand,Customer Strand,NormID
0,NaN,BovineHD2400000076,24,112601,NaN,NaN,NaN,NaN,NaN
1,NaN,BovineHD2400000069,24,163270,NaN,NaN,NaN,NaN,NaN
2,NaN,Hapmap54014-rs29018901,24,300821,NaN,NaN,NaN,NaN,NaN
3,NaN,BovineHD4100016339,24,335857,NaN,NaN,NaN,NaN,NaN
4,NaN,ARS-BFGL-NGS-103469,24,391651,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1532,NaN,BovineHD2400018199,24,61954180,NaN,NaN,NaN,NaN,NaN
1533,NaN,BTB-01890193,24,61991351,NaN,NaN,NaN,NaN,NaN
1534,NaN,BovineHD2400018253,24,62039634,NaN,NaN,NaN,NaN,NaN
1535,NaN,ARS-BFGL-NGS-29191,24,62127707,NaN,NaN,NaN,NaN,NaN
1536,NaN,BovineHD0700020755,24,62179612,NaN,NaN,NaN,NaN,NaN

In [4]:
manifest = pd.read_csv(
    "data/manifest/BovineHD_B1.csv", sep=",", skiprows=7, skipfooter=23, engine="python"
)

manifest

,IlmnID,Name,IlmnStrand,SNP,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,GenomeBuild,Chr,...,Species,Source,SourceVersion,SourceStrand,SourceSeq,TopGenomicSeq,BeadSetID,Exp_Clusters,Intensity_Only,RefStrand
0,ARS-BFGL-BAC-10172-0_T_F_1511662585,ARS-BFGL-BAC-10172,TOP,[A/G],29744436,GGTCCCCAAAGTATGTGGTAGCACTTACTTATGTAAGTCATCACTC...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,TOP,CTCAGAAGTTGGTCCCCAAAGTATGTGGTAGCACTTACTTATGTAA...,CTCAGAAGTTGGTCCCCAAAGTATGTGGTAGCACTTACTTATGTAA...,260,3,0,-
1,ARS-BFGL-BAC-1020-0_B_R_1511662870,ARS-BFGL-BAC-1020,BOT,[T/C],43711500,GGATTTTCTTCAATGTTGTTTCAGTGGCATCCTTTATTTGACTGGA...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,TOP,GGATTGAACTCAGGTCTCCTGATTTCTCACTGAGCCATCTGGGAAG...,GGATTGAACTCAGGTCTCCTGATTTCTCACTGAGCCATCTGGGAAG...,282,3,0,+
2,ARS-BFGL-BAC-10245-0_B_F_1511658502,ARS-BFGL-BAC-10245,BOT,[T/C],19677417,CGCCTTCTGTTTTTCTTCTTCTCTCTTCCTGTTCTCTTTCTCTCTG...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,BOT,CCCACTTCCCCGCCTTCTGTTTTTCTTCTTCTCTCTTCCTGTTCTC...,TCCTTTCTAGGAGGACAGGCCTGAGTGGGGGCCTGGGAGGGGAAGA...,260,3,0,-
3,ARS-BFGL-BAC-10345-0_T_F_1511662909,ARS-BFGL-BAC-10345,TOP,[A/C],20791343,ACCATTCATTCTATTGCTTTGTGCTTCAAGTACTCCTGCAAATAAA...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,TOP,GGTATAGGGCACCATTCATTCTATTGCTTTGTGCTTCAAGTACTCC...,GGTATAGGGCACCATTCATTCTATTGCTTTGTGCTTCAAGTACTCC...,260,3,0,-
4,ARS-BFGL-BAC-10365-0_T_R_1511658265,ARS-BFGL-BAC-10365,TOP,[A/C],20611360,CAGACTCACAGCACTAATTTCTCATCTTCTCCCAGCCAATGTTTAT...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,BOT,CAAAAACTTCAAGTGTATTATCCCGTTTATATTACACTCCTGAGGA...,GGCTTGTTGGCAGACTCACAGCACTAATTTCTCATCTTCTCCCAGC...,260,3,0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777957,UA-IFASA-9744-0_T_F_1511694619,UA-IFASA-9744,TOP,[A/G],60644483,TTGGAAATGGGTGGGAGGGGTGGATTCTGACCTAACTTATAACCAG...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,TOP,AACTGATGAATTGGAAATGGGTGGGAGGGGTGGATTCTGACCTAAC...,AACTGATGAATTGGAAATGGGTGGGAGGGGTGGATTCTGACCTAAC...,260,3,0,-
777958,UA-IFASA-9774-0_B_F_1511694984,UA-IFASA-9774,BOT,[T/C],46701302,AACTGTGGACATAGAATGTCACCTGCTGTATCAGAAAACAGCCATC...,NaN,NaN,UMD_3.1,14,...,Bos taurus,UM3,0,BOT,CTCACTATTAAACTGTGGACATAGAATGTCACCTGCTGTATCAGAA...,CTCATTTTCTCCATCCTGAATCCATTGGGGGTGGAGAAGGGGACGG...,260,3,0,-
777959,UA-IFASA-9790-0_B_F_1511694684,UA-IFASA-9790,BOT,[T/C],72800491,GGAGGGCGAGGCTCCCGTTTCTTCATTTAGCAGATGTTCATAGAGC...,NaN,NaN,UMD_3.1,19,...,Bos taurus,UM3,0,BOT,ACCCATGATGGGAGGGCGAGGCTCCCGTTTCTTCATTTAGCAGATG...,TCAAGCAAGGCCCCACCCATCTGCTCTCTGCTGAGTCCTCAAGGTC...,260,3,0,+
777960,UA-IFASA-9812-0_T_R_1511695089,UA-IFASA-9812,TOP,[A/G],23731397,GGAACGTTTCTCTTACGTTTCTCTGCGTGCTTGAGAAACTTCAGAT...,NaN,NaN,UMD_3.1,29,...,Bos taurus,UM3,0,BOT,GTAAAAACAAACCTCCATAGCTGATAGGAATGGTCTCAACTTGCAG...,TCCCTTTGCTGGAACGTTTCTCTTACGTTTCTCTGCGTGCTTGAGA...,282,3,0,-
777961,UA-IFASA-9813-0_T_R_1511694653,UA-IFASA-9813,TOP,[A/G],22637474,AACAGAAAGGACGTTGAGGTTCAATTTTAGACATGGGGGAATTGAC...,NaN,NaN,UMD_3.1,19,...,Bos taurus,UM3,0,BOT,AATAAAACCAACCTTTGCACTCGCTAACGGTTCAGCATTAATCAGA...,GAGTTTTGAAAACAGAAAGGACGTTGAGGTTCAATTTTAGACATGG...,260,3,0,+

In [ ]:
ref_panel_chr24 = pd.read_csv(
    "data/ref_panel/Chr24_phased_snp.vcf.gz",
    sep=r"\w+",
    skiprows=12,
    compression="gzip",
    low_memory=True,
)

ref_panel_chr24

/tmp/ipykernel_20/2046087215.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  ref_panel_chr24 = pd.read_csv(

In [ ]:
%%bash
# zip -9 /scratch/storageA/zaleski_bulls/bulls-vcf-pipeline/tests/data/raw/test_data.zip test_data_res_FinalReport.txt test_data_res_SampleMap.txt test_data_res_SNPMap.txt